plugins: [node, prettier]
env:
  node: true
  es6: true
parserOptions:
  ecmaVersion: 2021
  sourceType: module
extends:
  - plugin:import/errors
  - plugin:import/warnings
  - eslint:recommended
  - plugin:node/recommended
  - prettier
