##############################
# Netlify configuration file #
##############################

# List of Build plugins
[[plugins]]
package = "."
  [plugins.inputs]
    img_cache_local = true
    img_cache_local_dir = ['/img']

    img_cache_remote = true
    img_cache_remote_dir = '../.cache'

    img_cache_httpHeader = true

    other_cache_dir = []

[build]
    base = "./"
    command = "echo \"haha building!\""
    publish = "_site"

[build.environment]
NODE_VERSION = "12.18.0"
