##############################
# Netlify configuration file #
##############################

# List of Build plugins
[[plugins]]
package = "."
  [plugins.inputs]
  cache_img = false
  cache_img_httpHeader = true

  cache_assets = '../.cache'
  cache_other = []

[build]
    base = "./"
    command = "echo \"haha building!\""
    publish = "_site"

[build.environment]
NODE_VERSION = "12.18.0"
